Repository AjinkyaSahu/DSA, pull requests merged in 2021-10, with the labels that each got.

#6 stack added
  Stack/stack.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#3 catalan Added
  In Cpp/catalan.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#7 Counting Sort
  In Cpp/counting_sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#11 Selection Sort Added
  Heap Sort (VEDANT)/Heap_Sort.cpp
  Heap Sort (VEDANT)/Heap_Sort.exe
  Selection Sort (VEDANT)/Selection_sort.cpp
  Selection Sort (VEDANT)/Selection_sort.exe
Labels: hacktoberfest-accepted, hacktoberfest2021

#8 new folder created
  Sorting methods/Bubble_Sort/bubble_sort.py
  Sorting methods/Merge sort/merge_sort.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#12 Added a Tree Data Structure
  Tree/Binary_tree.cpp
  Tree/Binary_tree.exe
Labels: hacktoberfest-accepted, hacktoberfest2021

#13 adding RPN implementation using stacks in Python
  In Python/stack_rpn.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#18 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest2021

#19 Binary tree right view
  Tree/Binary tree right view
Labels: hacktoberfest-accepted, hacktoberfest2021

#15 Create queue.cpp
  Queue/queue.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#22 Modified some instructions
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest, easy, hacktoberfest-accepted, hacktoberfest2021

#20 Create 0-1knapsack.py #17
  In Python/0-1knapsack.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#21 Created Trie Data Structure
  Trie/trie.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#26 Create treeTraversal.py
  In Python/treeTraversal.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#24 Added QuickSort.cpp in In Cpp/ folder
  In Cpp/QuickSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#25 Create insertion_sort.py
  Insertion_sort/insertion_sort.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#23 Added Sieve of Eratosthenes Algorithm
  Number Theory/SieveOfEratosthenes.cpp
Labels: hacktoberfest2021

#37 Create Floyd's Triangle
  In Python/Floyd's Triangle
Labels: hacktoberfest-accepted, hacktoberfest2021

#34 added special type of linked list i.e. XOR linked list
  XOR Linked List/queueUsingXorLinkedList.c
  XOR Linked List/stackUsingXorLinkedLIst.c
  XOR Linked List/xorLinkedList.c
Labels: hacktoberfest-accepted, hacktoberfest2021

#35 Implemented Radix Sort using Bucket Sort
  In Cpp/RadixSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#36 Create Maximal square
  Dynamic programming/Maximal square
Labels: hacktoberfest-accepted, hacktoberfest2021

#27 C++ Code for Kadane's Algorithm
  In Cpp/kadaneAlgorithm.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#38 Top View of binary tree
  Tree/topView
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#43 Created longest_increasing_subsequence_dp.cpp
  Dynamic programming/longest_increasing_subsequence_dp.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#42 Create fibonacci.c
  fibonacci.c
Labels: hacktoberfest-accepted, hacktoberfest2021

#59 stack.c
  Stack/stack_1.c
Labels: hacktoberfest-accepted, hacktoberfest2021

#58 Added DFSAlgo
  In Cpp/DFSAlgo
Labels: hacktoberfest-accepted, hacktoberfest2021

#57 Create NQueenProblem.cpp
  In Cpp/NQueenProblem.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#56 Create BFSAlgo
  In Cpp/BFSAlgo
Labels: hacktoberfest-accepted, hacktoberfest2021

#55 Added 0-1 Knapsack Problem
  In Cpp/KnapsackProblem.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#53 Added linked list, doubly linked list and stack implementation
  DoublyLinkedList/DLinkedList.cpp
  In Cpp/template.cpp
  LinkedList/LinkedList.cpp
  Queue/queueUsingStack.cpp
  Stack/stackImplement.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#51 Add CPP code for Cyclic Redundancy Check error detection
  In Cpp/CyclicRedundencyCheck.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#50 Unique element.cpp
  In Cpp/Find the unique element.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#49 Added prims Algorithm in Python.
  In Python/prims.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#46 Create topview.py
  topview.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#45 Codechef DP problem Alternating subarray prefix solution
  Dynamic programming/Codechef_Dp_Alternating subarray prefix.cpp
Labels: hacktoberfest-accepted

#66 Discrepancy in README.md removed and guidelines updated
  README.md
Labels: hacktoberfest-accepted, hacktoberfest2021

#71 added huffman encoding
  In Cpp/huffman.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#60 Tic Tac Toe Game.py
  In Python/Tic Tac Toe Game.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#69 Added question check palindrome(recursively).cpp
  In Cpp/Check palindrome(recursively).cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#68 Added question all indices of number with solution
  In Cpp/All indices of number.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#67 Added ques does s contains t with solution
  In Cpp/Does s contains t.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#64 The code has been added with easy explanation in C++.
  Tree/Sum of nodes at level k.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#63 SpeechRecognition.py
  In Python/SpeechRecognition.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#61 HANGMAN GAME(Star Wars Edition).py
  In Python/HANGMAN GAME.py
Labels: hacktoberfest2021

#81 Created tree inheritance
  Tree/inheritance.c
Labels: hacktoberfest-accepted, hacktoberfest2021

#79 Create CircularLinkedList.cpp
  LinkedList/CircularLinkedList.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#77 Create InsertNodeDoublyLinkedList.cpp
  LinkedList/InsertNodeDoublyLinkedList.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#78 Create DeleteNodeDoublyLinkedList.cpp
  LinkedList/DeleteNodeDoublyLinkedList.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#76 Added Minimum Edit Sequence
  Dynamic programming/minEditSeq.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#75 Add Code for Subset Sum DP
  Dynamic programming/SubsetSum.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#72 Added program that calculates GCD
  Number Theory/GCD.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021
